### ISSUE TITLE
Feltöltés

### ISSUE THREAD

**Issue by DaWe35** [DaWe35/marstorage#10]
- Multiple file upload
- Show uploading files in a small window
![google-drive-startin-uploads](https://user-images.githubusercontent.com/10603822/99903014-de034a80-2cc1-11eb-87a1-3ab40286954a.png)

- maybe we don't need the 'upload' page. Just open the local-file-browser when clicking upload

**Comment by DanielMozes** [comment]
Fixed by 1e16a376e83e39d7870e227d802fee1fcb2f6985
